# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "priam"
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kenji Hara"]
  s.date = "2013-02-25"
  s.description = "Command-base client for Cassandra."
  s.email = "haracane@gmail.com"
  s.executables = ["priam"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/priam",
    "lib/priam.rb",
    "lib/priam/command.rb",
    "lib/priam/command/cql.rb",
    "lib/priam/command/cql/create.rb",
    "lib/priam/command/delete.rb",
    "lib/priam/command/get.rb",
    "lib/priam/command/help.rb",
    "lib/priam/command/insert.rb",
    "lib/priam/command/put.rb",
    "lib/priam/core.rb",
    "lib/priam/core/common.rb",
    "lib/priam/core/get.rb",
    "priam.gemspec",
    "spec/bin/priam_spec.rb",
    "spec/lib/priam/command/delete_spec.rb",
    "spec/lib/priam/command/get_spec.rb",
    "spec/lib/priam/command/insert_spec.rb",
    "spec/lib/priam/command/put_spec.rb",
    "spec/lib/priam/core/common_spec.rb",
    "spec/lib/priam_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/haracane/priam"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Command-base client for Cassandra."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<thrift>, ["~> 0.7.0"])
      s.add_runtime_dependency(%q<thrift_client>, ["~> 0.7.1"])
      s.add_runtime_dependency(%q<simple_uuid>, ["~> 0.2.0"])
      s.add_runtime_dependency(%q<cassandra>, ["~> 0.12.1"])
      s.add_runtime_dependency(%q<json>, [">= 1.6.5"])
      s.add_development_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<ci_reporter>, [">= 1.7.0"])
      s.add_development_dependency(%q<flog>, [">= 3.2.0"])
    else
      s.add_dependency(%q<thrift>, ["~> 0.7.0"])
      s.add_dependency(%q<thrift_client>, ["~> 0.7.1"])
      s.add_dependency(%q<simple_uuid>, ["~> 0.2.0"])
      s.add_dependency(%q<cassandra>, ["~> 0.12.1"])
      s.add_dependency(%q<json>, [">= 1.6.5"])
      s.add_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<ci_reporter>, [">= 1.7.0"])
      s.add_dependency(%q<flog>, [">= 3.2.0"])
    end
  else
    s.add_dependency(%q<thrift>, ["~> 0.7.0"])
    s.add_dependency(%q<thrift_client>, ["~> 0.7.1"])
    s.add_dependency(%q<simple_uuid>, ["~> 0.2.0"])
    s.add_dependency(%q<cassandra>, ["~> 0.12.1"])
    s.add_dependency(%q<json>, [">= 1.6.5"])
    s.add_dependency(%q<rspec>, [">= 2.8.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<ci_reporter>, [">= 1.7.0"])
    s.add_dependency(%q<flog>, [">= 3.2.0"])
  end
end

